const menuItems = {
  PRODUCT: [
    { name: "Watch Demo", linkTo: "/" },
    { name: "Pricing", linkTo: "/" },
    { name: "Paid vs. Free", linkTo: "/" },
    { name: "Accessibility", linkTo: "/" },
    { name: "Featured Releases", linkTo: "/" },
    { name: "Changelog", linkTo: "/" },
    { name: "Status", linkTo: "/" },
  ],
  FEATURES: [
    { name: "Channels", linkTo: "/" },
    { name: "Slack Connect", linkTo: "/" },
    { name: "Workflow Builder", linkTo: "/" },
    { name: "Messaging", linkTo: "/" },
    { name: "Huddles", linkTo: "/" },
    { name: "Canvas", linkTo: "/" },
    { name: "Lists", linkTo: "/" },
    { name: "Clips", linkTo: "/" },
    { name: "Search", linkTo: "/" },
    { name: "Apps & Integrations", linkTo: "/" },
    { name: "File Sharing", linkTo: "/" },
    { name: "Slack AI", linkTo: "/" },
    { name: "Security", linkTo: "/" },
    { name: "Enterprise Key Management", linkTo: "/" },
    { name: "Slack Atlas", linkTo: "/" },
  ],
  SOLUTIONS: [
    { name: "Engineering", linkTo: "/" },
    { name: "IT", linkTo: "/" },
    { name: "Customer Service", linkTo: "/" },
    { name: "Sales", linkTo: "/" },
    { name: "Project Management", linkTo: "/" },
    { name: "Marketing", linkTo: "/" },
    { name: "Security", linkTo: "/" },
    { name: "Technology", linkTo: "/" },
    { name: "Media", linkTo: "/" },
    { name: "Financial Services", linkTo: "/" },
    { name: "Retail", linkTo: "/" },
    { name: "Public Sector", linkTo: "/" },
    { name: "Education", linkTo: "/" },
    { name: "Health & Life Sciences", linkTo: "/" },
    { name: "See all solutions", linkTo: "/" },
  ],
  RESOURCES: [
    { name: "Help Center", linkTo: "/" },
    { name: "What’s New", linkTo: "/" },
    { name: "Resources Library", linkTo: "/" },
    { name: "Slack Blog", linkTo: "/" },
    { name: "Community", linkTo: "/" },
    { name: "Customer Stories", linkTo: "/" },
    { name: "Events", linkTo: "/" },
    { name: "Developers", linkTo: "/" },
    { name: "Partners", linkTo: "/" },
    { name: "Partner Offers", linkTo: "/" },
    { name: "App Directory", linkTo: "/" },
    { name: "Slack Certified", linkTo: "/" },
  ],
  COMPANY: [
    { name: "About Us", linkTo: "/" },
    { name: "News", linkTo: "/" },
    { name: "Media Kit", linkTo: "/" },
    { name: "Brand Center", linkTo: "/" },
    { name: "Careers", linkTo: "/" },
    { name: "Swag Store", linkTo: "/" },
    { name: "Engineering Blog", linkTo: "/" },
    { name: "Design Blog", linkTo: "/" },
    { name: "Contact Us", linkTo: "/" },
  ],
  WHYSLACK: [
    { name: "Slack vs. Email", linkTo: "/" },
    { name: "Enterprise", linkTo: "/" },
    { name: "Small Business", linkTo: "/" },
    { name: "Productivity", linkTo: "/" },
    { name: "Task Management", linkTo: "/" },
    { name: "Scale", linkTo: "/" },
    { name: "Trust", linkTo: "/" },
  ],
};

export default menuItems;
